language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - extra-android-support
    - extra-android-m2repository

before_install:
 - chmod +x gradlew

script:
    - cd app
    - ../gradlew assembleRelease